In [103]:
import pandas as pd
import numpy as np

test = pd.read_csv("test-data.csv")
train = pd.read_csv("train-data.csv")

test.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price
0,0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26 km/kg,998 CC,58.2 bhp,4.0,NaN
1,1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,24.7 kmpl,796 CC,47.3 bhp,5.0,NaN
2,2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,13.68 kmpl,2393 CC,147.8 bhp,7.0,25.27 Lakh
3,3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,23.59 kmpl,1364 CC,null bhp,5.0,NaN
4,4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN

In [104]:
train.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [105]:
# print(train['Name'].nunique())
# print(train['Location'].nunique())
# print(train['Fuel_Type'].nunique())
# print(train['Transmission'].nunique())
# print(train['Owner_Type'].nunique())

# simplified
for i in ['Name', 'Location', 'Fuel_Type', 'Transmission', 'Owner_Type']:
    print(f"number of unique values for {i} are:", train[i].nunique())

number of unique values for Name are: 1876
number of unique values for Location are: 11
number of unique values for Fuel_Type are: 5
number of unique values for Transmission are: 2
number of unique values for Owner_Type are: 4

In [106]:
train['Brand'] = train['Name'].str.split().str[0]
print(train['Brand'].nunique())
print(train['Brand'].value_counts().head(10))

train.head()

31
Brand
Maruti           1211
Hyundai          1107
Honda             608
Toyota            411
Mercedes-Benz     318
Volkswagen        315
Ford              300
Mahindra          272
BMW               267
Audi              236
Name: count, dtype: int64

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Brand
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,Maruti
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,Hyundai
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,Honda
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,Maruti
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,Audi

In [107]:
print(train.shape)
print(train.isnull().sum())
train.describe()

(6019, 15)
Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  42
New_Price            5195
Price                   0
Brand                   0
dtype: int64

        Unnamed: 0         Year  Kilometers_Driven        Seats        Price
count  6019.000000  6019.000000       6.019000e+03  5977.000000  6019.000000
mean   3009.000000  2013.358199       5.873838e+04     5.278735     9.479468
std    1737.679967     3.269742       9.126884e+04     0.808840    11.187917
min       0.000000  1998.000000       1.710000e+02     0.000000     0.440000
25%    1504.500000  2011.000000       3.400000e+04     5.000000     3.500000
50%    3009.000000  2014.000000       5.300000e+04     5.000000     5.640000
75%    4513.500000  2016.000000       7.300000e+04     5.000000     9.950000
max    6018.000000  2019.000000       6.500000e+06    10.000000   160.000000

In [108]:
print(train['Mileage'].dtype)
train['Mileage'].head()

train.dtypes

object

Unnamed: 0             int64
Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                float64
New_Price             object
Price                float64
Brand                 object
dtype: object

In [109]:
# Extracting numbers with regular expression

# Breaking down the pattern ([\d.]+):

# \d → match any digit (0-9)
# . → match a decimal point
# [ ] → match any character inside these brackets — so [\d.] means "digit or decimal point"
# + → one or more of the previous character
# ( ) → capture this match and return it


train['Mileage'] = train['Mileage'].str.extract(r'([\d.]+)').astype(float)
train['Engine'] = train['Engine'].str.extract(r'([\d.]+)').astype(float)
train['Power'] = train['Power'].str.extract(r'([\d.]+)').astype(float)

print(train[['Mileage', 'Engine', 'Power']].head())

   Mileage  Engine   Power
0    26.60   998.0   58.16
1    19.67  1582.0  126.20
2    18.20  1199.0   88.70
3    20.77  1248.0   88.76
4    15.20  1968.0  140.80

In [110]:
#checking for specific data

train[train["Engine"]==5998.000000]

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Brand
5521,5521,Bentley Continental Flying Spur,Hyderabad,2006,48000,Petrol,Automatic,First,8.6,5998.0,552.0,4.0,NaN,59.0,Bentley

In [111]:
train.dtypes

Unnamed: 0             int64
Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage              float64
Engine               float64
Power                float64
Seats                float64
New_Price             object
Price                float64
Brand                 object
dtype: object

In [112]:
train.drop('New_Price', axis = 1, inplace = True)
train.drop('Unnamed: 0', axis = 1, inplace = True)
train.drop('Name', axis = 1, inplace = True)

In [113]:
train.head()

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75,Maruti
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,Hyundai
2,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50,Honda
3,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00,Maruti
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,Audi

In [114]:
#Handling missing values

# Dropping or filling with median.

#train.dropna(inplace=True)
#train.isnull().sum()

for col in ['Mileage', 'Engine', 'Power', 'Seats']:
    median_val = train[col].median()
    train[col].fillna(median_val, inplace=True)
    print(f"{col} median: {median_val}")

# Verify
print(train.isnull().sum())

Mileage median: 18.15
Engine median: 1493.0
Power median: 97.7
Seats median: 5.0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
Brand                0
dtype: int64

/var/folders/47/n441r75n6xz_pth9vyhvp_th0000gn/T/ipykernel_88104/2723583545.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train[col].fillna(median_val, inplace=True)

In [115]:
# Number of unique values in each object features. Useful insight for encoding

train.select_dtypes(include=object).nunique()

Location        11
Fuel_Type        5
Transmission     2
Owner_Type       4
Brand           31
dtype: int64

In [116]:
# Actual encoding

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in ['Transmission', 'Owner_Type', 'Location', 'Brand']:
    train[col] = le.fit_transform(train[col])

# One hot encoding for Fuel_Type
train = pd.get_dummies(train, columns=['Fuel_Type'], drop_first=True)

print(train.head())
print(train.dtypes)

   Location  Year  Kilometers_Driven  Transmission  Owner_Type  Mileage  \
0         9  2010              72000             1           0    26.60
1        10  2015              41000             1           0    19.67
2         2  2011              46000             1           0    18.20
3         2  2012              87000             1           0    20.77
4         3  2013              40670             0           2    15.20

   Engine   Power  Seats  Price  Brand  Fuel_Type_Diesel  Fuel_Type_Electric  \
0   998.0   58.16    5.0   1.75     18             False               False
1  1582.0  126.20    5.0  12.50     10              True               False
2  1199.0   88.70    5.0   4.50      9             False               False
3  1248.0   88.76    7.0   6.00     18              True               False
4  1968.0  140.80    5.0  17.74      1              True               False

   Fuel_Type_LPG  Fuel_Type_Petrol
0          False             False
1          False             False
2          False              True
3          False             False
4          False             False
Location                int64
Year                    int64
Kilometers_Driven       int64
Transmission            int64
Owner_Type              int64
Mileage               float64
Engine                float64
Power                 float64
Seats                 float64
Price                 float64
Brand                   int64
Fuel_Type_Diesel         bool
Fuel_Type_Electric       bool
Fuel_Type_LPG            bool
Fuel_Type_Petrol         bool
dtype: object

In [117]:
train.head()

,Location,Year,Kilometers_Driven,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol
0,9,2010,72000,1,0,26.60,998.0,58.16,5.0,1.75,18,False,False,False,False
1,10,2015,41000,1,0,19.67,1582.0,126.20,5.0,12.50,10,True,False,False,False
2,2,2011,46000,1,0,18.20,1199.0,88.70,5.0,4.50,9,False,False,False,True
3,2,2012,87000,1,0,20.77,1248.0,88.76,7.0,6.00,18,True,False,False,False
4,3,2013,40670,0,2,15.20,1968.0,140.80,5.0,17.74,1,True,False,False,False

In [118]:
# Convert boolean columns to integers
bool_cols = train.select_dtypes(include='bool').columns
train[bool_cols] = train[bool_cols].astype(int)

train.head()

,Location,Year,Kilometers_Driven,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol
0,9,2010,72000,1,0,26.60,998.0,58.16,5.0,1.75,18,0,0,0,0
1,10,2015,41000,1,0,19.67,1582.0,126.20,5.0,12.50,10,1,0,0,0
2,2,2011,46000,1,0,18.20,1199.0,88.70,5.0,4.50,9,0,0,0,1
3,2,2012,87000,1,0,20.77,1248.0,88.76,7.0,6.00,18,1,0,0,0
4,3,2013,40670,0,2,15.20,1968.0,140.80,5.0,17.74,1,1,0,0,0